apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/management-components-version: v0.26.0-dev+build.2
  name: release-i-03782-12b5075
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: 196.18.142.31
    machineGroupRef:
      kind: VSphereMachineConfig
      name: release-i-03782-12b5075-cp
    machineHealthCheck:
      maxUnhealthy: 100%
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: release-i-03782-12b5075
  eksaVersion: v0.26.0-dev+build.2
  externalEtcdConfiguration:
    count: 1
    machineGroupRef:
      kind: VSphereMachineConfig
      name: release-i-03782-12b5075-etcd
  gitOpsRef:
    kind: FluxConfig
    name: eksa-test
  kubernetesVersion: "1.36"
  licenseToken: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJsaWNlbnNlSWQiOiJsLTAxMTNhZjZiOWY4OTRlZGU5NzhkYWEzYmRlZGUwYjc4IiwibGljZW5zZVZlcnNpb24iOiIxIiwiYmVnaW5WYWxpZGl0eSI6IjIwMjUtMDItMjVUMDA6MzA6NDMuMDAwWiIsImVuZFZhbGlkaXR5IjoiMjAyOC0wMi0yNlQwMDozMDo0My4wMDBaIiwic3Vic2NyaXB0aW9uSWQiOiJiMWM0NmNmMS04YzVlLTQzN2QtYTJjYy00MTdiMDZmOWI0Y3I6ZmU4M2MzOTciLCJzdWJzY3JpcHRpb25OYW1lIjoiYm90dGxlcm9ja2V0LWVrc2EtdGVzdHMiLCJhY2NvdW50SWQiOiI2NTkzNTYzOTg0MDQiLCJyZWdpb24iOiJ1cy13ZXN0LTIifQ.7QZj679HcQHYwQnQuZRZDaugigc-gQnxMbIL_1fftq6xwxZ2WtOU3xha8_zK6TE4n2wbCXgnbdNljrSbdCKI5w
  machineHealthCheck:
    maxUnhealthy: 100%
    nodeStartupTimeout: 10m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: release-i-03782-12b5075
  packages:
    disable: true
  workerNodeGroupConfigurations:
  - count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: release-i-03782-12b5075
    machineHealthCheck:
      maxUnhealthy: 40%
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: release-i-03782-12b5075
  namespace: default
spec:
  datacenter: SDDC-Datacenter
  insecure: true
  network: /SDDC-Datacenter/network/sddc-cgw-network-3
  server: 196.18.64.136
  thumbprint: ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: release-i-03782-12b5075-cp
  namespace: default
spec:
  cloneMode: fullClone
  datastore: /SDDC-Datacenter/datastore/WorkloadDatastore
  diskGiB: 25
  folder: /SDDC-Datacenter/vm
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool
  template: /SDDC-Datacenter/vm/Templates/kubernetes-1-36-eks-4-ubuntu-2204
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBf1/Emrhv/E5r1us9kaW+I0rvdDWIWCgVSw+OGQbQ4ofvQbTp+AVswOqGDccAaZ2yJhiL/r5nRz5ioCqMWGWsoGAwxlCNmAU3/SeQOloNNQwQ872wexJDWX13wc4YvxHdxMQV1zkAXpHe2tz5r4RFG+kB7P87RawLp2f+qIRUyviW8YGk8o7aTfhOG0NVjeqFH+HMxCY/J6ubaxlSiiJGxKDfOuRAoZMzkV98rqJqxwUjmt4O/O9nHklbh7V6ivBKvJU4mdiu/Yh0wkOG0FrIO14UF4FyfHh45y8omwrdSfmxlAaqf6G7wo/1SvdWoTVVfBeHWy04Tx18Pb9ltfenUPW17UzYK1arx9xagV6VdZIMjFngSdqlkqjKBMJT99n1lh9L8rdQlUAxSafzFmH8dwAD2Fa9R1zkWYnLZYCCabbjWsXNae6+arx5v2VMB4hrFZVxgh8O/vmPGE2IAsx9SEx9mk8sE+opbWDH3Z5KLoFi4laQz7chCPxg+DmDIqcTTUAgzq6mAFdBZK2gBoBed97kFxD/1Y0YVEmB6RCHBVtQcoJNtmNN5QbIGmnU4SPxNmanmAi1o0kUd73wlvMaa8TfeWrWvMkTNIqg6dwtmhOtRwKyy4DhvZL51iFwdZRygDXuhoZKr7e9MGN1CPht30v/WAP8UsagoO73rFb6HQ==
      eksae2e@email.com

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: release-i-03782-12b5075
  namespace: default
spec:
  cloneMode: fullClone
  datastore: /SDDC-Datacenter/datastore/WorkloadDatastore
  diskGiB: 25
  folder: /SDDC-Datacenter/vm
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool
  template: /SDDC-Datacenter/vm/Templates/kubernetes-1-36-eks-4-ubuntu-2204
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBf1/Emrhv/E5r1us9kaW+I0rvdDWIWCgVSw+OGQbQ4ofvQbTp+AVswOqGDccAaZ2yJhiL/r5nRz5ioCqMWGWsoGAwxlCNmAU3/SeQOloNNQwQ872wexJDWX13wc4YvxHdxMQV1zkAXpHe2tz5r4RFG+kB7P87RawLp2f+qIRUyviW8YGk8o7aTfhOG0NVjeqFH+HMxCY/J6ubaxlSiiJGxKDfOuRAoZMzkV98rqJqxwUjmt4O/O9nHklbh7V6ivBKvJU4mdiu/Yh0wkOG0FrIO14UF4FyfHh45y8omwrdSfmxlAaqf6G7wo/1SvdWoTVVfBeHWy04Tx18Pb9ltfenUPW17UzYK1arx9xagV6VdZIMjFngSdqlkqjKBMJT99n1lh9L8rdQlUAxSafzFmH8dwAD2Fa9R1zkWYnLZYCCabbjWsXNae6+arx5v2VMB4hrFZVxgh8O/vmPGE2IAsx9SEx9mk8sE+opbWDH3Z5KLoFi4laQz7chCPxg+DmDIqcTTUAgzq6mAFdBZK2gBoBed97kFxD/1Y0YVEmB6RCHBVtQcoJNtmNN5QbIGmnU4SPxNmanmAi1o0kUd73wlvMaa8TfeWrWvMkTNIqg6dwtmhOtRwKyy4DhvZL51iFwdZRygDXuhoZKr7e9MGN1CPht30v/WAP8UsagoO73rFb6HQ==
      eksae2e@email.com

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/etcd: "true"
  name: release-i-03782-12b5075-etcd
  namespace: default
spec:
  cloneMode: fullClone
  datastore: /SDDC-Datacenter/datastore/WorkloadDatastore
  diskGiB: 25
  folder: /SDDC-Datacenter/vm
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool
  template: /SDDC-Datacenter/vm/Templates/kubernetes-1-36-eks-4-ubuntu-2204
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBf1/Emrhv/E5r1us9kaW+I0rvdDWIWCgVSw+OGQbQ4ofvQbTp+AVswOqGDccAaZ2yJhiL/r5nRz5ioCqMWGWsoGAwxlCNmAU3/SeQOloNNQwQ872wexJDWX13wc4YvxHdxMQV1zkAXpHe2tz5r4RFG+kB7P87RawLp2f+qIRUyviW8YGk8o7aTfhOG0NVjeqFH+HMxCY/J6ubaxlSiiJGxKDfOuRAoZMzkV98rqJqxwUjmt4O/O9nHklbh7V6ivBKvJU4mdiu/Yh0wkOG0FrIO14UF4FyfHh45y8omwrdSfmxlAaqf6G7wo/1SvdWoTVVfBeHWy04Tx18Pb9ltfenUPW17UzYK1arx9xagV6VdZIMjFngSdqlkqjKBMJT99n1lh9L8rdQlUAxSafzFmH8dwAD2Fa9R1zkWYnLZYCCabbjWsXNae6+arx5v2VMB4hrFZVxgh8O/vmPGE2IAsx9SEx9mk8sE+opbWDH3Z5KLoFi4laQz7chCPxg+DmDIqcTTUAgzq6mAFdBZK2gBoBed97kFxD/1Y0YVEmB6RCHBVtQcoJNtmNN5QbIGmnU4SPxNmanmAi1o0kUd73wlvMaa8TfeWrWvMkTNIqg6dwtmhOtRwKyy4DhvZL51iFwdZRygDXuhoZKr7e9MGN1CPht30v/WAP8UsagoO73rFb6HQ==
      eksae2e@email.com

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: eksa-test
  namespace: default
spec:
  branch: aws-eks-anywhere-test-vsphere-release-0-26-fd5da21a-fac5-4acc-be60-7d013c264dd3-197
  clusterConfigPath: aws-eks-anywhere-test-vsphere-release-0-26-fd5da21a-fac5-4acc-be60-7d013c264dd3-197
  git:
    repositoryUrl: ssh://git@github.com/that-jetpack-guy/aws-eks-anywhere-test-vsphere-release-0-26-fd5da21a-fac5-4acc-be60-7d013c264dd3-197.git
  systemNamespace: default

---
